### ISSUE TITLE
Cannot compile on Unreal Engine 5.0.3

### ISSUE THREAD

**Issue by fpibbs** [bakjos/FFMPEGMedia#43]
Cannot compile on Unreal Engine 5.0.3 C++ project

` Running C:/DEV/UE_5.0/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.exe  -projectfiles -project="C:/Users/DEV/Desktop/MyProject/MyProject.uproject" -game -rocket -progress -log="C:\Users\DEV\Desktop\MyProject/Saved/Logs/UnrealVersionSelector-2022.09.18-19.16.16.log"
Log file: C:\Users\DEV\Desktop\MyProject\Saved\Logs\UnrealVersionSelector-2022.09.18-19.16.16.log
Log file: C:\Users\DEV\AppData\Local\UnrealBuildTool\Log_GPF.txt

Some Platforms were skipped due to invalid SDK setup: IOS, Linux, LinuxArm64.
See the log file for detailed information

Discovering modules, targets and source code for project...
C:\Users\DEV\Desktop\MyProject\Plugins\FFMPEGMedia-master\FFMPEGMedia.uplugin: warning: Unknown platform Win32 while parsing allow list for module descriptor FFMPEGMedia
C:\Users\DEV\Desktop\MyProject\Plugins\FFMPEGMedia-master\FFMPEGMedia.uplugin: warning: Unknown platform Win32 while parsing allow list for module descriptor FFMPEGMediaFactory
C:\Users\DEV\Desktop\MyProject\Plugins\FFMPEGMedia-master\Source\FFMPEGMediaFactory\FFMPEGMediaFactory.Build.cs(48,49): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
C:\Users\DEV\Desktop\MyProject\Plugins\FFMPEGMedia-master\Source\FFMPEGMedia\FFMPEGMedia.Build.cs(44,99): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
C:\Users\DEV\Desktop\MyProject\Plugins\FFMPEGMedia-master\Source\FFMPEGMedia\FFMPEGMedia.Build.cs(111,42): error CS7036: There is no argument given that corresponds to the required formal parameter 'Value' of 'ModuleRules.ReceiptPropertyList.Add(string, string)'
ERROR: Expecting to find a type to be declared in a target rules named 'MyProjectTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
`

Has anyone tried?

**Comment by Anulo2** [comment]
Same, can't compile :/

**Comment by kzerot** [comment]
Seems UE5 hasn't win32 target, so just remove it from Build.cs file.
