### ISSUE TITLE
FFMPEGMedia isn't rebuilding in 4.24.2

### ISSUE THREAD

**Issue by arnekalypse** [bakjos/FFMPEGMedia#6]
Hey guys,

as the topic says. I'm currently try to rebuild the plugin with UE 4.24.2. 

`LogInit: Warning: Incompatible or missing module: FFMPEGMedia
LogInit: Warning: Incompatible or missing module: FFMPEGMediaFactory
Running C:/Program Files/Epic Games/UE_4.24/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="C:/Users/grafikadm/Documents/Unreal Projects/FFMPEG/FFMPEG.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Invalidating makefile for FFMPEGEditor (FFMPEGMedia.uplugin has been added)
... LibrariesPath -> C:\Users\grafikadm\Documents\Unreal Projects\FFMPEG\Plugins\FFMPEGMedia-master\ThirdParty\ffmpeg\lib\vs\x64
@progress push 5%
Parsing headers for FFMPEGEditor
  Running UnrealHeaderTool "C:\Users\grafikadm\Documents\Unreal Projects\FFMPEG\FFMPEG.uproject" "C:\Users\grafikadm\Documents\Unreal Projects\FFMPEG\Intermediate\Build\Win64\FFMPEGEditor\Development\FFMPEGEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for FFMPEGEditor in 7,7615705 seconds
@progress pop
Building FFMPEGEditor...
Using Visual Studio 2019 14.24.28316 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 12 actions with 48 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 8%
  [1/12] Default.rc2
  @progress 'Compiling C++ source code...' 17%
  [2/12] Default.rc2
  @progress 'Compiling C++ source code...' 25%
  [3/12] SharedPCH.CoreUObject.NonOptimized.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 33%
  [4/12] Module.FFMPEGMediaFactory.cpp
  C:/Users/grafikadm/Documents/Unreal Projects/FFMPEG/Plugins/FFMPEGMedia-master/Source/FFMPEGMediaFactory/Private/FFMPEGMediaFactoryModule.cpp(17): fatal error C1083: Datei (Include) kann nicht ge?ffnet werden: "WindowsHWrapper.h": No such file or directory
  @progress 'Compiling C++ source code...' 42%
  [5/12] Module.FFMPEGMediaFactory.gen.cpp
  @progress 'Compiling C++ source code...' 50%
  [6/12] SharedPCH.Engine.NonOptimized.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 58%
  [7/12] Module.FFMPEGMedia.cpp
  C:\Users\grafikadm\Documents\Unreal Projects\FFMPEG\Plugins\FFMPEGMedia-master\Source\FFMPEGMedia\Private\FFMPEG\CondWait.h(4): fatal error C1083: Datei (Include) kann nicht ge?ffnet werden: "ScopeLock.h": No such file or directory
LogInit: Warning: Still incompatible or missing module: FFMPEGMedia
LogInit: Warning: Still incompatible or missing module: FFMPEGMediaFactory
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.`

Thanks for any help or advices. 

Regards

Arne

**Comment by PTS93** [comment]
Working fine on Windows with 4.24.
Maybe try to build with VS 2017 instead? According to the log it can't find a few includes.

**Comment by arnekalypse** [comment]
Hey PTS93,

it doesn't work. I've tried it on a complete new machine with just vs2017, ue 4.24 and ffmpeg.  

Do i need any special prerequisites befort I start the rebuild process? 

Thanks.

**Comment by PTS93** [comment]
Sorry, not sure what the issue is then. Maybe you included it in a non C++ project?
You do not need ffmpeg seperately, dll is already included here.
I'm on Windows 10 though don't think that makes a difference.

**Comment by arnekalypse** [comment]
Do you have a compiled plugin for 4.24? If yes, can you send me a packed version of your plugin? 

That would be great.

**Comment by PTS93** [comment]
Sure, copy that into the plugin folder
[Binaries.zip](https://github.com/bakjos/FFMPEGMedia/files/4317990/Binaries.zip)

**Comment by arnekalypse** [comment]
Thanks. I think the binaries folder is not enough, the engine needs more to start without rebuilding.

With 4.19 it is no problem to rebuild the plugin... strange...

**Comment by PTS93** [comment]
Sorry I noticed I compiled it in a 4.23 project. Though still works in even 4.25 preview for me. The binary is all it needs. Try this one this is definitely 4.25 now:
[Binaries.zip](https://github.com/bakjos/FFMPEGMedia/files/4320109/Binaries.zip)

**Comment by arnekalypse** [comment]
These are the project binaries. Not the plugin's. 
Thank you very much.

**Comment by PTS93** [comment]
Uf sorry long process. Double checked, definitely 4.24 now. I edited the previous post (meant to write 4.24 not 4.25)

**Comment by arnekalypse** [comment]
Wow. It's working. You helped me a lot, thanks.

**Comment by bakjos** [comment]
@PTS93 Thanks for looking into this issue, @arnekalypse  I just checked using the version 4.24.3 and VS 2019 and it's compiling correctly, so I'm going to close this one
